### ISSUE TITLE
Max depth would aid visualisation

### ISSUE THREAD

**Issue by stevennnd** [desiguel/alembic-revision-graph#1]
My project has a ridiculous number of alembic revisions. This makes the force graph pretty unwealdy. I'm usually only interested in what's going on somewhere near the head. Would it be possible to add a parameter to limit the depth? (e.g. I'd love to just see the "top 20" - though I understand this is non-trivial due to branching etc.).

Thanks Andre :D

**Comment by desiguel** [comment]
Good idea. I just added a max depth parameter (-d)... pruning the tree was a little tricky but doable. The versions directory arg has also been named (-v).
